Feature/wm/footer/vertical list
mmarkiewicz1/ItechArtWrapper pull request #10
Opened 2021-08-09 08:04 UTC by wmosienski

2021-08-09 10:12 UTC, sergeevds requested changes

2021-08-09 10:12 UTC, sergeevds commented on src/core/VerticalList/VerticalList.jsx
> +const VerticalList = ({ children, ...listProps }) => <List {...listProps}>{children}</List>;
let's make one component List which can be used props `orientation` instead of `HorizontalList` and `VerticalList`

2021-08-09 10:13 UTC, wmosienski commented on src/core/VerticalList/VerticalList.jsx
> +const VerticalList = ({ children, ...listProps }) => <List {...listProps}>{children}</List>;
k

2021-08-10 09:37 UTC, wmosienski commented on src/core/VerticalList/VerticalList.jsx
> +const VerticalList = ({ children, ...listProps }) => <List {...listProps}>{children}</List>;
@sergeevds done, now it is List with 'vertical' prop

2021-08-10 20:28 UTC, solleOlle commented on src/core/Divider/Divider.jsx
> +        borderColor: primary ? text.primary : text.tertiary
secondary? :)
we have to think how it's better to do this
not readable for me...

2021-08-10 20:29 UTC, solleOlle commented on src/core/Divider/Divider.jsx
> +        padding: 'auto 0'
why? what advantages this line has?

2021-08-10 20:31 UTC, solleOlle commented on src/core/List/List.jsx
> +        flexDirection: props.vertical ? 'column' : 'row',
why we can have a property like `vertical` (true or false) instead of `direction` that can be 'column' or 'row'?

2021-08-10 20:32 UTC, solleOlle commented on src/core/List/List.jsx
> +            <div className={classes.flex}>{children}</div>
why so many divs?

2021-08-10 20:34 UTC, solleOlle commented on src/core/List/List.jsx
> +        display: 'inline-block'
why?

2021-08-11 08:08 UTC, wmosienski commented on src/core/List/List.jsx
> +        display: 'inline-block'
@solleOlle 
it makes elements of the list occupy as much space as they have to, but not as much as they want...
in other words: Typography as an element makes the list full width and therefore the divider is full width, which looks like this:
![image](https://user-images.githubusercontent.com/87005572/128991010-dfee52c6-2973-4113-b30d-482d6d546cb4.png)

and the behaviour of the list should look like this:
![image](https://user-images.githubusercontent.com/87005572/128991632-d5019dfc-6e47-4b44-88be-3804de161628.png)

UPDATE: the itechart.com has just changed its look... and the list occupies as much space as it wants:
![image](https://user-images.githubusercontent.com/87005572/128992464-cfe11b5e-730c-479a-a97d-720c4eb02ae5.png)

questions:
1) was my solution ok before the site update? or should this display (or any other approach) be handeled in other place?

conclusions:
I'm removing this display: inline-block, because after the update it's not necessary

2021-08-11 08:16 UTC, wmosienski commented on src/core/Divider/Divider.jsx
> +        borderColor: primary ? text.primary : text.tertiary
ok, we will have to add more options to the theme... I will add divider key alongside text key in the theme, and it will have primary and secondary color

2021-08-11 08:41 UTC, wmosienski commented on src/core/Divider/Divider.jsx
> +        borderColor: primary ? text.primary : text.tertiary
done, divider was already in use by the theme underneath, so I put "myDivider" with primary and secondary color

2021-08-11 08:45 UTC, wmosienski commented on src/core/Divider/Divider.jsx
> +        padding: 'auto 0'
right, I removed it and the behaviur of divider is the same. I pushed commit with the removal

2021-08-11 08:47 UTC, wmosienski commented on src/core/List/List.jsx
> +        flexDirection: props.vertical ? 'column' : 'row',
I thought it would be cleaner way just to use vertical prop and leave other styles in ...props, because it is the most common use case - changing only flex direction

2021-08-11 08:48 UTC, wmosienski commented on src/core/List/List.jsx
> +            <div className={classes.flex}>{children}</div>
it's covered in the following discusion:
https://github.com/mmarkiewicz1/ItechArtWrapper/pull/10#discussion_r686599144

2021-08-11 10:28 UTC, solleOlle approved these changes

2021-08-11 10:32 UTC, sergeevds approved these changes

2021-08-11 10:55 UTC, merged