Fixture/mm/header/button
mmarkiewicz1/ItechArtWrapper pull request #13
Opened 2021-08-11 07:40 UTC by mmarkiewicz1

2021-08-11 10:30 UTC, solleOlle commented on src/core/StyledButton/StyledButton.jsx
> +            borderColor: '#ffffff',
why? we have it on 44 line

2021-08-11 10:31 UTC, solleOlle commented on src/stories/core/TopMenuButton/TopMenuButton.stories.jsx
> +    //color: 'primary'
please remove it

2021-08-11 10:31 UTC, solleOlle approved these changes

2021-08-11 10:40 UTC, sergeevds requested changes

2021-08-11 10:40 UTC, sergeevds commented on src/core/ButtonWrapper/ButtonWrapper.jsx
> +    }
```
root: ({ fontSize, fontWeight, color }) => ({
        fontSize,
        fontWeigh,
        color
 })
```

2021-08-11 10:40 UTC, sergeevds commented on src/core/TopMenuButton/TopMenuButton.jsx
> +};
you use only `size` and `text` props.

2021-08-11 10:40 UTC, sergeevds commented on src/core/StyledButton/StyledButton.jsx
> +    text: PropTypes.string
StyledButton has to support all props from ButtonWrapper

2021-08-11 10:40 UTC, sergeevds commented on src/core/StyledButton/StyledButton.jsx
> +        borderColor: '#ea3d26',
can we add the color in theme?

2021-08-13 14:02 UTC, wmosienski requested changes

2021-08-13 14:18 UTC, wmosienski commented on src/core/TopMenuButton/TopMenuButton.jsx
> +const useStyles = makeStyles(({ size }) => ({
here you have theme, not props

2021-08-13 14:22 UTC, wmosienski requested changes

2021-08-13 14:22 UTC, wmosienski commented on src/core/TopMenuButton/TopMenuButton.jsx
> +        '@media (min-width: 900px)': {
since you added breakpoints to the theme, you could use it here

2021-08-13 14:22 UTC, wmosienski commented on src/theme/theme.jsx
> +        // fontFamily: [IBMPlexSansLight.fontFamily, 'Arial', 'sans-serif'].join(','),
you know what to do :)

2021-08-13 15:02 UTC, mmarkiewicz1 commented on src/core/TopMenuButton/TopMenuButton.jsx
> +        '@media (min-width: 900px)': {
done :+1:

2021-08-17 12:09 UTC, mmarkiewicz1 commented on src/theme/theme.jsx
> +        // fontFamily: [IBMPlexSansLight.fontFamily, 'Arial', 'sans-serif'].join(','),
done

2021-08-17 12:09 UTC, mmarkiewicz1 commented on src/core/TopMenuButton/TopMenuButton.jsx
> +const useStyles = makeStyles(({ size }) => ({
done

2021-08-17 12:15 UTC, mmarkiewicz1 commented on src/theme/theme.jsx
> +            xs: 400,
.

2021-08-17 14:41 UTC, merged