Feature/mo/header/menu link
mmarkiewicz1/ItechArtWrapper pull request #4
Opened 2021-07-30 06:07 UTC by MagdaITechArt

2021-08-02 11:01 UTC, solleOlle commented on .storybook/preview.js
> +import React from 'react';
preview for what? not really nice file name

2021-08-03 13:46 UTC, solleOlle commented
why it's so huge?

2021-08-03 13:52 UTC, solleOlle commented on src/core/MenuLink/MenuLink.jsx
> +    const arrowRotation = isArrowRotation ? classes.arrowRotation : '';
weird 2 lines..

2021-08-03 13:54 UTC, solleOlle commented on src/core/MenuLink/MenuLink.jsx
> +            onMouseLeave={arrow && changeLinkArrowActivity}
why don't you check `arrow` value into `changeLinkArrowActivity` function?

2021-08-03 16:07 UTC, solleOlle commented on src/core/MenuLink/MenuLink.jsx
> +            onMouseLeave={arrow && changeLinkArrowActivity}
cc @sergeevds 
what do you think about it?

2021-08-05 07:58 UTC, MagdaITechArt commented on .storybook/preview.js
> +import React from 'react';
Yeah, like we talked about it, it is config file from storybook

2021-08-05 08:56 UTC, MagdaITechArt commented on src/core/MenuLink/MenuLink.jsx
> +            onMouseLeave={arrow && changeLinkArrowActivity}
fixed

2021-08-05 08:57 UTC, MagdaITechArt commented on src/core/MenuLink/MenuLink.jsx
> +    const arrowRotation = isArrowRotation ? classes.arrowRotation : '';
I'll fixed it in feature/mo/header/menu-link-lists

2021-08-05 09:00 UTC, MagdaITechArt commented
> why it's so huge?

I've removed unnecessary fonts

2021-08-09 06:22 UTC, solleOlle commented on src/core/MenuLink/MenuLink.jsx
> +                bottom: 'calc(75% - 23px)',
😏  it's not really clear. could you please put a comment about magic numbers? 🙏 
the same for 61 and 68 lines

2021-08-09 06:24 UTC, solleOlle commented on src/core/MenuLink/MenuLink.jsx
> +        !mobileView && goTo();
we can have one condition with `if (mobileView) {} else {}` logic

2021-08-09 06:26 UTC, solleOlle commented on src/core/MenuLink/MenuLink.jsx
> +            href={route ? route : '#'}
you could use `{ route || '#' }` here

2021-08-09 06:57 UTC, MagdaITechArt commented on src/core/MenuLink/MenuLink.jsx
> +                bottom: 'calc(75% - 23px)',
The same here, I 've been get rid of that in my last commit. https://github.com/MartinITechArt/ItechArtWrapper/pull/6/commits/f5d21fcf6f56967723b5bfa2558553b304b8def2
I made a lot of changes here, there is no MenuLink only ArrowLink without calc. I think it's better check there, sorry for that mess... :(

2021-08-09 06:59 UTC, MagdaITechArt commented on src/core/MenuLink/MenuLink.jsx
> +        !mobileView && goTo();
the same here, sorry :(

2021-08-09 07:01 UTC, MagdaITechArt commented on src/core/MenuLink/MenuLink.jsx
> +            href={route ? route : '#'}
the same here, sorry :(

2021-08-10 09:01 UTC, sergeevds requested changes

2021-08-10 09:01 UTC, sergeevds commented on src/index.js
> +            <Router>
don't think that we need routing in this repo

2021-08-10 09:01 UTC, sergeevds commented on src/theme/theme.jsx
> +            xl: 1920
is it some kind ovveride default values?

2021-08-10 12:10 UTC, mozieblo2 commented on package.json
> +        "react-router-dom": "^5.2.0",
I 've been removed it

2021-08-10 12:10 UTC, mozieblo2 commented on src/core/Divider/Divider.jsx
> +        margin: '7 0'
yes, why does it not? :)

2021-08-10 12:11 UTC, mozieblo2 commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +        <Box component="div">
fixed

2021-08-10 12:11 UTC, mozieblo2 commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +            />
yes, fixed

2021-08-10 12:11 UTC, mozieblo2 commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +LinkAlignedWithIcon.propTypes = {
fixed

2021-08-10 12:11 UTC, mozieblo2 commented on src/core/LinkArrow/LinkArrow.jsx
> +                    />
fixed

2021-08-10 12:11 UTC, mozieblo2 commented on src/core/LinkArrow/LinkArrow.jsx
> +    return renderLink();
fixed

2021-08-10 12:12 UTC, mozieblo2 commented on src/core/LinkWrapper/LinkWrapper.jsx
> +        target: '_self'
added

2021-08-10 12:12 UTC, mozieblo2 commented on src/core/LinkWrapper/LinkWrapper.jsx
> +        }
refactored

2021-08-10 12:12 UTC, mozieblo2 commented on src/core/MenuLinkList/MenuLinkList.jsx
> +import { MENU_LINKS } from 'mocks/MENU_LINKS';
ok, fixed

2021-08-10 12:12 UTC, mozieblo2 commented on src/core/MenuLinkList/MenuLinkList.jsx
> +            {MENU_LINKS.map(({ title, route, isArrow, links }, index) => {
fixed

2021-08-10 12:13 UTC, mozieblo2 commented on src/index.js
> +            <Router>
ok, removed

2021-08-10 12:13 UTC, mozieblo2 commented on src/theme/theme.jsx
> +            xl: 1920
yes, I've checked it on itechArt website and try to adjust the width

2021-08-10 19:55 UTC, solleOlle commented on src/core/Divider/Divider.jsx
> +        padding: 'auto 0'
what it gives?

2021-08-10 20:03 UTC, solleOlle commented on src/core/Divider/Divider.jsx
>          borderWidth: !vertical ? `${dividerSize[size]}px 0 0 0` : `0 ${dividerSize[size]}px 0 0`
maybe it will be easier to use border bottom/right for a block?
![image](https://user-images.githubusercontent.com/1507285/128927299-2ec5a18c-551c-49af-9711-2274e2bf2b52.png)

2021-08-10 20:20 UTC, solleOlle commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +            top: '63%',
I think it's better to put an icon after a link name ...
we will have magic numbers like this for different icons
what do you think?

2021-08-10 20:22 UTC, solleOlle commented on src/core/LinkArrow/LinkArrow.jsx
> +            fontSize: fontSize * 0.45,
could we put magic numbers (this line - 0.45 and 25 and 28) to some readable variable here?

2021-08-10 20:23 UTC, solleOlle commented on src/core/LinkArrow/LinkArrow.jsx
> +                height: size * 0.45,
do we use meta tag viewport?

2021-08-10 20:23 UTC, solleOlle commented on src/core/LinkArrow/LinkArrow.jsx
> +        if (isMobileView || (!isMobileView && isArrow)) {
please update this function too :)

2021-08-11 06:36 UTC, mozieblo2 commented on src/core/Divider/Divider.jsx
> +        padding: 'auto 0'
I don't know really, eslint just added a coma here, it is not my line of code :P

2021-08-11 06:56 UTC, mozieblo2 commented on src/core/Divider/Divider.jsx
>          borderWidth: !vertical ? `${dividerSize[size]}px 0 0 0` : `0 ${dividerSize[size]}px 0 0`
ok, but divider isn't my component, I try to use it, should I fixed it? :P

2021-08-11 07:08 UTC, mozieblo2 commented on src/core/LinkArrow/LinkArrow.jsx
> +        if (isMobileView || (!isMobileView && isArrow)) {
ok, fixed

2021-08-11 07:26 UTC, mozieblo2 commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +            top: '63%',
Do you mean not to use ::before and ::after? only flex? I think we talked about it and you said that it doesn't matter... maybe I misunderrstood something? :P

2021-08-11 07:31 UTC, mozieblo2 commented on src/core/LinkArrow/LinkArrow.jsx
> +                height: size * 0.45,
I try to adjust fontSize to iTechArt page, but you have right it looks wierd, fixed

2021-08-11 07:31 UTC, mozieblo2 commented on src/core/LinkArrow/LinkArrow.jsx
> +            fontSize: fontSize * 0.45,
I try to adjust fontSize to iTechArt page, but you have right it looks wierd, fixed

2021-08-11 07:37 UTC, mozieblo2 commented on src/core/LinkArrow/LinkArrow.jsx
> +                height: size * 0.45,
yes, we use, but I don't understand why are you asking? :)

2021-08-11 09:55 UTC, mozieblo2 commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +            top: '63%',
I'm trying to change it, but it doesn't make much sense to me. First of all, the hover does not work on the icon, if we add the icon separately, I will have to write a separate css for it? And secondly it doesn't bother the magic number because I will have to set the icon to the text and for the icon down I also have to use the magic value, so I don't know if it's a good idea but maybe I'm doing it wrong, I really don't know .. but for this way we will not avoid magic numbers when positioning anyway, what do you think?

2021-08-11 10:24 UTC, solleOlle commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +            top: '63%',
you could put an icon inside a link :)

2021-08-11 10:26 UTC, solleOlle approved these changes

2021-08-11 10:32 UTC, mozieblo2 commented on src/core/LinkAlignedWithIcon/LinkAlignedWithIcon.jsx
> +            top: '63%',
yes, I try this also, but I have to positioning icon there too..

2021-08-11 10:33 UTC, sergeevds approved these changes

2021-08-11 11:08 UTC, merged